#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6448813967                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=dev.jhale.binaryclock                                         # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Turn an old phone into a nerdy binary clock to show off your inner genius!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Joseph Hale
your_link                                 : https://jhale.dev
your_city                                 :                                 
email_address                             : support@jhale.dev
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : jhaledev
github_username                           : thehale/BinaryClock
youtube_username                          : "@JosephHale"
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Brightness Controls
    description                           : Perfect visibility day or night.
    fontawesome_icon_name                 : sun

  - title                                 : Show/Hide Hints
    description                           : Learn how the clock works, or show off to your friends.
    fontawesome_icon_name                 : lightbulb

  - title                                 : Battery Friendly
    description                           : A pure black background is your AMOLED's best friend.
    fontawesome_icon_name                 : battery-full

  - title                                 : Landscape or Portrait
    description                           : Horizontal or vertical? Doesn't matter. Both are available and look great!
    fontawesome_icon_name                 : sync-alt

  - title                                 : Open Source
    description                           : Contributors of any skill level are invited to help build the app.
    fontawesome_icon_name                 : github
    fontawesome_icon_type                 : social


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#060b0d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - google_play

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
