# Mobile App Landing Page Configuration

# App Info
app_name            : Landing
app_description     : Wherever some that and kiwi that well 
                      dolphin alas this the mindfully jeepers 
                      one aside canny one preparatory up less therefore 
                      hello oh amid goodness checked.
app_price           : 4.99
ios_app_id          : 718043190
android_app_id      :

# Icon, screenshot and header image
app_icon            : ../assets/appicon-1024px.png  # Will automatically populate if you have set the iOS app id.
app_video           : # ../assets/video.mp4         # Uncomment and replace with path to app preview video. Optimal resolutions: 1242x2688 or 1125x2436.
app_screenshot      : ../assets/screenshot.png      # Will automatically populate if you have set the iOS app id.
header_image        : ../assets/headerimage.png     # Replace with custom background image or link to background image.

# Social Links
facebook_username   : 
twitter_username    : ebaehr
github_username     : emilbaehr
email_address       : emil.baehr@gmail.com

# Features
features                      :
  - title                     : Feature 1
    description               : Present the features of your app with the dynamic Jekyll theme
    fontawesome_icon_name     : magic
  - title                     : Feature 2
    description               : Show your app in the context of an iPhone
    fontawesome_icon_name     : mobile
  - title                     : Feature 3
    description               : Adjust colors, backgrounds and typography
    fontawesome_icon_name     : adjust

# Theme Settings
accent_color                             : "#1d63ea"
primary_text_color                       : "#000000"
secondary_text_color                     : "#666666"

header_color                             : "#000000"
header_transparency                      : 0.1

image_overlay_color                      : "#363b3d"
image_overlay_transparency               : 0.6

feature_icons_foreground_color           : "#1d63ea"
feature_icons_background_color           : "#e6e6e6"

social_icons_foreground_color            : "#666666"
social_icons_background_color            : "#e6e6e6"


# Analytics 
google_analytics              : # Enter Google Analytics tracking code (e.g. UA-2110908-2)





# # # # # # # # # # # # # # # #
# Jekyll-specific Config Below

# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
collections:
  posts:
    output          : true

# Handling Reading
safe                : false
include             : [".htaccess", "_pages"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/",]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : []

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Outputting
permalink           : date
paginate_path       : /page:num
timezone            : null

quiet               : false
verbose             : false
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Markdown Processors
rdiscount:
  extensions        : []

redcarpet:
  extensions        : []

kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : 1..6
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false