name: "Android"

on:
  push:
    branches: ["master", "ci"]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build Application
        run: |
          cd android
          ./gradlew bundleRelease

