name: "Standard Checks"

on:
  push:
    branches: ["master", "ci"]

jobs:
  check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Check lint rules
        run: yarn lint
      - name: Run JavaScript Tests
        run: yarn test

