name: "iOS"

on:
  push:
    branches: ["master", "ci"]

jobs:
  build:
    timeout-minutes: 25
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      - name: Install Node dependencies
        run: yarn install
      - name: Setup Cocoapods [cache]
        uses: actions/cache@v4
        id: cocoapods-cache
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-
      - name: Install CocoaPods
        run: yarn pods
      - name: Build Application
        run: |
          echo $SECRETS_TAR_GZ_B64 | base64 -d | tar -xz -C fastlane
          bundle exec fastlane ios build
        env:
          SECRETS_TAR_GZ_B64: ${{ secrets.SECRETS_TAR_GZ_B64 }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          RUBYOPT: '-rostruct' # Workaround for "NameError: uninitialized constant Fastlane::OpenStruct" (source: https://github.com/fastlane/fastlane/issues/21944#issuecomment-2045244250)
